### ISSUE TITLE
Add LÖVE Nuklear Definitions

### ISSUE THREAD

**Issue by goldenstein64** [LuaLS/LLS-Addons#10]
### What is the Addon for?

Add definitions for [keharriso/love-nuklear](https://github.com/keharriso/love-nuklear), a UI and window management adapter library for Love2D.

### Additional Notes

The definitions are stored at [goldenstein64/love-nuklear-definitions](https://github.com/goldenstein64/love-nuklear-definitions). I'm open to making a new branch to remove any miscellaneous config files.

**Comment by carsakiller** [comment]
Hello!

Any license files are fine to include, but a new branch would be nice to keep misc. files to a minimum 🙂

When you are ready to publish, please [open a pull request](https://github.com/LuaLS/LLS-Addons/blob/main/CONTRIBUTING.md#adding-an-addon) on this repo that adds a `love_nuklear` directory to `addons/` like so:
```
📂 love_nuklear/
    ├──📜 info.json
    └── 📁 module/
        ├── 📁 library/
        ├── 📄LICENSE
        └── 📜 config.lua
```
If you are publishing under a different branch, your addon would be added like so:
`git submodule add -b $BRANCH_NAME $HTTP_CLONE_URL addons/love_nuklear/module`
