### ISSUE TITLE
The Powder Toy Lua API Addon

### ISSUE THREAD

**Issue by Maticzpl** [LuaLS/LLS-Addons#128]
### What is the Addon for?

Add definitions for [The Powder Toy Lua API](https://powdertoy.co.uk/Wiki/W/Powder_Toy_Lua_API.html).
> The Powder Toy Lua API is a set of objects and functions that allow control over most aspects of the game, including graphics, element interactions, and interfaces. 

### Additional Notes

The repo for the addon is here: https://github.com/Maticzpl/TPT-LuaAPI-Addon

**Comment by carsakiller** [comment]
The PR was reverted due to a syntax error in the JSON. Please correct the error and open a new pull request.
