### ISSUE TITLE
A broken link

### ISSUE THREAD

**Issue by serg3295** [LuaLS/LLS-Addons#17]
The link to cc-tweaked/module is broken.
[module @ 143e735](https://github.com/LuaLS/LLS-Addons/blob/main/addons/cc-tweaked/module)

**Comment by carsakiller** [comment]
I noticed that as well. Unfortunately, [this is a GitHub issue](https://github.com/orgs/community/discussions/49626). `cc-tweaked` lives on GitLab, and it seems GitHub simply links to its own domain with the user and project name simply appended.
