### ISSUE TITLE
Garry's Mod submodule tag removal

### ISSUE THREAD

**Issue by luttje** [LuaLS/LLS-Addons#171]
For the future:

The garrysmod submodule in this repo has some faulty tags I pushed. I've removed them upstream, but no amount of pulling or pushing on my side can get the submodule here to delete them.

Could someone with permission to push to this repo please delete them?

```sh
cd addons/garrysmod/module
git push --delete origin "2023-04-08_18-02-22"
git push --delete origin "2023-04-10_08-43-08"
git push --delete origin "2023-04-10_21-17-13"
```

It'll get rid of these:
![faulty tags](https://github.com/user-attachments/assets/2dd71489-0a13-4eff-b4eb-47ae4963c38f)

Thanks

**Comment by carsakiller** [comment]
I believe this is actually a problem with the addon manager. It should be `git fetch --tags --force`-ing to grab the latest tags from the remote for each addon. I forgot this during my rushed fix last week.
