### ISSUE TITLE
adding Luvit addon

### ISSUE THREAD

**Issue by Bilal2453** [LuaLS/LLS-Addons#4]
### What is the Addon for?

This addon adds definitions for the [Luvit](https://luvit.io/) framework, a Lua framework that mimics the Node.js API making use of the Libuv backend bindings, [Luv](https://github.com/luvit/luv).

### Additional Notes

The meta definitions for this are at https://github.com/Bilal2453/luvit-meta, is it fine for the root directory to contain more than just the `library` and `config.json`? like the `README.md`, or should I create a branch that contains just those two `library`/`config.json`?

**Comment by carsakiller** [comment]
Hello! 👋

Just a README would be fine, but there is also the `scrapers/` directory and some other miscellaneous files. Making a new branch would be favourable to keep the size to a minimum 🙂.

When you are ready to publish, please [open a pull request](https://github.com/LuaLS/LLS-Addons/blob/main/CONTRIBUTING.md#adding-an-addon) on this repo that adds a `luvit` directory with the children `info.json` and `module/` (which is your new branch as a submodule) using [`git submodule add -b NEW_BRANCH CLONE_URL`](https://www.vogella.com/tutorials/GitSubmodules/article.html#submodules_trackbranch)

**Comment by Bilal2453** [comment]
By the way, how are updates to the definitions handled?  We just PR an update to the submodule I presume? Because sadly the submodule has to be pointing at a specific commit instead of latest whatever commit on a branch I believe

**Comment by carsakiller** [comment]
Yes, so when you have an update, you open another PR that updates the submodule
