### ISSUE TITLE
Unbound API definitions

### ISSUE THREAD

**Issue by Wolf-64** [LuaLS/LLS-Addons#73]
### What is the Addon for?

Adds definitions for the Lua API of [Unbound](https://www.unbound.io/), a game engine currently in development and in a (very) early-access phase.

### Additional Notes

The engine and it’s API are closed source. Having these definitions in an easy to access space (via the addon manager in VS Code) would provide a quick setup for current testers, and later on any developer using Unbound for developing their games.

**Comment by carsakiller** [comment]
Hmm. I think we should get permission from the developers first before publishing this addon. Seeing as the engine is only in limited access, closed source, and I couldn't find any evidence/documentation of their API from searching around the web, they may not want their API to public like this.

What do you think would be the best way to get in touch with them?

**Comment by Wolf-64** [comment]
I understand your concerns. Actually I already am in touch with them on their Discord. Their API documentation (from which I generate the definitions) is not posted publicly but accessible via Help button in-engine. 

So far, they haven’t given explicit permission, but expressed concerns whether or not an addon like mine would even be accepted here, as it’s a proprietary API for a closed source project.

If you say it wouldn’t be a problem, I’ll reach out again to get explicit permission and discuss the visibility matter along the way.
If you’d like to jump in on the matter yourself, your best bet is the Unbound Discord, as they’re very responsive.
Otherwise there’s their public email: hello@unbound.io

**Comment by Wolf-64** [comment]
I’ve checked back with them and they’re absolutely fine with it. If there’s any proof you need of their statement before continuing do let me know!

**Comment by fhoenig** [comment]
Hey. Creator of Unbound here. There is no issue in publishing this. It's fantastic. Thank you @Wolf-64.

(also all the LUA code of the main application that Unbound is CC-BY-NC, open source)

**Comment by carsakiller** [comment]
Alright, perfect! Just wanted to make sure first.

**Comment by Wolf-64** [comment]
Hi again, I'm trying to go through the contribution workflow, but my lack of experience with git and especially submodules - which I've never touched before - is getting in my way. So I would like to ask for more specific pointers on how to create and properly commit a submodule.

So far I've forked the LLS-Addons repo as per the instructions. I have created a folder for my addon to the repo structure like "LLS-Addons/addons/unbound-api". There I've created an "info.json" and a "module" folder, then copied my addon into that folder. So now I've got:

- LLS-Addons/addons/unbound-api/modules/info.json
- LLS-Addons/addons/unbound-api/modules/library/*.lua
- LLS-Addons/addons/unbound-api/modules/config.json

I fail to properly register and commit a submodule, having tried multiple versions of the command:
"git submodule add https://github.com/Wolf-64/LLS-Addons.git addons/unbound-api", including the "module" folder will throw a git error ("... already exists and is not a valid git repo") while the given command here does seem to create a submodule, but I'm unable to actually add my files for a commit, as they continue to be marked as modified/untracked while "git add addons/unbound-api" gives no results.

Any pointers on how to go on from here would be greatly appreciated!

**Comment by carsakiller** [comment]
The Git submodule command will do the copying for you. To recover, try these steps:

1. `git reset HEAD --hard` **This will remove all changes to LLS-Addons you have made**
2. If `git status` shows that the submodule still exists, you may need to run `git submodule remove path/to/submodule`
    - The correct path to use is `addons/unbound-api/module`, but you mentioned using `addons/unbound-api` so it may be that.
3. Create `LLS-Addons/addons/unbound-api/` directory
4. Run `git submodule add https://github.com/Wolf-64/LLS-Addons.git addons/unbound-api/module`
5. You can now create your `info.json` in the `addons/unbound-api` directory
6. Run `git add .` to add all changes (includes `.gitmodules` and the actual module at `addons/unbound-api/module`
7. Commit your changes and push
8. Open a PR to merge your changes

**Comment by carsakiller** [comment]
I just noticed, you seem to be adding LLS-Addons as a submodule as well, not your unbound API definitions repo
