### ISSUE TITLE
Question: How to make my type definitions an addon?

### ISSUE THREAD

**Issue by cloudwindy** [LuaLS/LLS-Addons#74]
### What is the Addon for?

Add definitions for the [Mirai Project](https://github.com/cloudwindy/mirai).

**Comment by cloudwindy** [comment]
This is my personal project at first, but I later decided to make it open source. Is this qualified for library/project?

**Comment by carsakiller** [comment]
Sure! Instructions can be found in [the wiki](https://luals.github.io/wiki/addons/#creating-an-addon) and in the [CONTRIBUTING](https://github.com/LuaLS/LLS-Addons/blob/main/CONTRIBUTING.md).

**Comment by cloudwindy** [comment]
[Done](https://github.com/cloudwindy/mirai-types).

**Comment by cloudwindy** [comment]
Ah, am I supposed to push to [LuaCATS](https://github.com/LuaCATS)?

**Comment by carsakiller** [comment]
To publish it to the [addon manager](https://luals.github.io/wiki/addons/#addon-manager), you open a PR here, see [CONTRIBUTING](https://github.com/LuaLS/LLS-Addons/blob/main/CONTRIBUTING.md#publishing-the-addon).
