### ISSUE TITLE
Add Penlight Definitions

### ISSUE THREAD

**Issue by goldenstein64** [LuaLS/LLS-Addons#8]
### What is the Addon for?

Adds definitions for [lunarmodules/Penlight](https://github.com/lunarmodules/Penlight), a general-purpose library.

> Penlight brings together a set of generally useful pure Lua modules, focusing on input data handling (such as reading configuration files), functional programming (such as map, reduce, placeholder expressions, etc), and OS path management. Much of the functionality is inspired by the Python standard libraries.

### Additional Notes

The definitions are at [goldenstein64/pl-definitions](https://github.com/goldenstein64/pl-definitions). I'm open to making a branch to remove the `LICENSE` and other config files.

**Comment by carsakiller** [comment]
Hello!

Any license files are fine to include, but a new branch would be nice to keep misc. files to a minimum 🙂

When you are ready to publish, please [open a pull request](https://github.com/LuaLS/LLS-Addons/blob/main/CONTRIBUTING.md#adding-an-addon) on this repo that adds a `penlight` directory to `addons/` like so:
```
📂 penlight/
    ├──📜 info.json
    └── 📁 module/
        ├── 📁 library/
        ├── 📄LICENSE
        └── 📜 config.lua
```
If you are publishing under a different branch, your addon would be added like so:
`git submodule add -b $BRANCH_NAME $HTTP_CLONE_URL addons/penlight/module`

**Comment by goldenstein64** [comment]
Is it okay to include a README as well? You said it was okay in the luvit issue, #4, but I want to be sure.

**Comment by carsakiller** [comment]
It should be easy enough for people to find the repository that the addon originates from (that would include a README). To keep things as small as possible, I think it *would* be best to omit the README.

I am still ironing out the process for creating and publishing addons as there are a lot of cogs to the machine that makes this work. I have edited the [CONTRIBUTING](https://github.com/LuaLS/LLS-Addons/blob/main/CONTRIBUTING.md) to hopefully clear things up some more.

**Comment by goldenstein64** [comment]
> I would very much appreciate it if definition for penlight could be added to LLS-Addons! Any progress?

Sorry, I've been busy with other projects. I would say it's complete as-is, so I'll make a PR
