### ISSUE TITLE
Add definitions for the Local Lua Debugger

### ISSUE THREAD

**Issue by b0mbie** [LuaLS/LLS-Addons#86]
### What is the Addon for?

Add definitions for [Local Lua Debugger](https://github.com/tomblind/local-lua-debugger-vscode/)'s Lua interface library, `lldebugger`.
Local Lua Debugger is a VSCode extension that provides debugging support for Lua.

### Additional Notes

The `lldebugger` library isn't fully formally documented, from what I could find, maybe apart from `lldebugger.start()` and `lldebugger.requestBreak()`.
I have inspected the source code for the library and found out the definitions for the functions that I could find in the `lldebugger` table.

**Comment by carsakiller** [comment]
Closed by https://github.com/LuaLS/LLS-Addons/pull/87
