### ISSUE TITLE
Add argparse Definitions

### ISSUE THREAD

**Issue by goldenstein64** [LuaLS/LLS-Addons#9]
### What is the Addon for?

Adds definitions for [luarocks/argparse](https://github.com/luarocks/argparse), a library for parsing command-line arguments.

### Additional Notes

The definitions are located at [goldenstein64/argparse-definitions](https://github.com/goldenstein64/argparse-definitions). I'm open to making a branch to remove the `LICENSE` and other config files.

**Comment by carsakiller** [comment]
Hello!

Any license files are fine to include, but a new branch would be nice to keep misc. files to a minimum 🙂

When you are ready to publish, please [open a pull request](https://github.com/LuaLS/LLS-Addons/blob/main/CONTRIBUTING.md#adding-an-addon) on this repo that adds a `argparse` directory to `addons/` like so:
```
📂 argparse/
    ├──📜 info.json
    └── 📁 module/
        ├── 📁 library/
        ├── 📄LICENSE
        └── 📜 config.lua
```
If you are publishing under a different branch, your addon would be added like so:
`git submodule add -b $BRANCH_NAME $HTTP_CLONE_URL addons/love_nuklear/module`
